debug: true
spring:
  activemq:
    broker-url: tcp://192.168.25.128:61616

alidayu:
  accessKeyId: LTAI5tGqETuaEYfwics92ijy
  accessKeySecret: xka1W6qxQLZVeCX0UFDfWUphKAIvAY
  signName: 阿里云短信测试
  templateCode: SMS_154950909

server:
  port: 9106