debug: true
spring:
  activemq:
    broker-url: tcp://192.168.25.128:61616

alidayu:
  accessKeyId: LTAI5tGqET
  accessKeySecret: xka1W6q
  signName: 阿里云短信测试
  templateCode: SMS

server:
  port: 9106